# the configuration version (do not change this)
version: 7

# How long (in ticks, 20ticks/second) to wait after someone opens a backpack before they can open it again
openBackpackCooldown: 8

# Max number of backpacks that can be put into a combined backpack (cannot be more than 9)
maxNumberOfCombinedBackpacks: 9

# What language to set the plugin to. You can compile the plugin to support any languages you wish. For more info, see the github.
# Current included languages are: en (English), es (Spanish), it (Italian), fr (French), zh (Chinese), pl (Polish), de (German)
language: en

# Uses extra resources but will track furnace backpacks wherever they go to update them on the completion of the smelting operation
# Note: the backpack will always be located if it remains in the player who started the smelting operation's inventory
trackFurnaceBackpacks: true

recipes:
  small:
    display_name: "&aSmall Backpack"
    lore:
      - "A tiny little backpack. Great for short"
      - "trips and such."
    ingredients:
      A: OAK_PLANKS
      B: LEATHER
    shape:
      - "AAA"
      - "ABA"
      - "AAA"
  large:
    display_name: "&aLarge Backpack"
    lore:
      - "A big boy capable of storing a lot"
      - "of items."
    ingredients:
      A: OAK_LOG
      B: IRON_INGOT
    shape:
      - "AAA"
      - "ABA"
      - "AAA"
  linked:
    display_name: "&aLinked Backpack"
    lore:
      - "A mystical bag capable of transiting items across"
      - "dimensions to a predetermined location. Legend says"
      - "that the bag will link to any container you wack with"
      - "it."
    ingredients:
      A: DIAMOND
      B: LEATHER
      C: ENDER_EYE
      D: IRON_INGOT
    shape:
      - "ADA"
      - "BCB"
      - "ADA"
  combined:
    display_name: "&aCombined Backpack"
    lore:
      - "A bag capable of storing multiple backpacks"
      - "for easy use."
    ingredients:
      A: GOLD_INGOT
      C: LEATHER
    shape:
      - "CAC"
      - "A A"
      - "CAC"
  craft:
    display_name: "&aCrafting Backpack"
    lore:
      - "A portable workbench for all of your on the"
      - "go crafting needs."
    ingredients:
      A: LEATHER
      B: CRAFTING_TABLE
    shape:
      - " A "
      - "ABA"
      - " A "
  ender:
    display_name: "&aEnder Backpack"
    lore:
      - "An ender chest in convenient backpack form."
    ingredients:
      A: ENDER_EYE
      B: OBSIDIAN
      C: LEATHER
    shape:
      - "CBC"
      - "BAB"
      - "CBC"
  furnace:
    display_name: "&aFurnace Backpack"
    lore:
      - "A portable furnace in a backpack that will"
      - "smelt all your items."
    ingredients:
      A: LEATHER
      B: FURNACE
    shape:
      - " A "
      - "ABA"
      - " A "
  backpack_key:
    ingredients:
      A: IRON_INGOT
      B: FEATHER
    shape:
      - "  A"
      - " BA"
      - " AA"